wip: add net/http to hertz
hertz-contrib/migrate pull request #7
Opened 2024-01-31 07:10 UTC by Skyenought

#### What type of PR is this?

#### What this PR does / why we need it (en: English/zh: Chinese):

en: 
zh:

#### Which issue(s) this PR fixes:

2024-01-31 07:20 UTC, li-jin-gou commented on cmd/net/internal/log/log.go
> +type Logger struct {
使用标准库提供的日志

2024-01-31 07:21 UTC, li-jin-gou commented on cmd/net/internal/args/args.go
> +	fset.StringVar(&a.TargetDir, "target-dir", "", "target directory")
理想状态应该一个目标的 dir 就可以。

2024-01-31 07:22 UTC, li-jin-gou commented on cmd/net/internal/args/args.go
> +	fset.StringVar(&a.TargetDir, "target-dir", "", "target directory")
不需要单独的文件，就一个参数

2024-02-02 07:09 UTC, Skyenought commented on cmd/net/internal/args/args.go
> +	fset.StringVar(&a.TargetDir, "target-dir", "", "target directory")
这是我用于测试的 flag

2024-02-06 11:14 UTC, li-jin-gou requested changes
Hertz 的 import_path 中的 github.com/cloudwego/hertz 抽成一个用户可修改参数，默认是开源的，内部需要修改

2024-02-06 11:14 UTC, li-jin-gou commented on cmd/net/internal/args/args.go
> +	fset.StringVar(&a.Filepath, "filepath", "./testdata/server.go", "file to translate")
这个是制定的那个文件？

2024-02-06 11:14 UTC, li-jin-gou commented on cmd/net/internal/utils/utils.go
> +				astutil.AddImport(fset, file, "context")
基础库需要去重，判断是否重复 import

2024-02-06 18:19 UTC, li-jin-gou commented on cmd/net/internal/logic/netHttp/packHttpSetCookie.go
> +package netHttp
空文件

2024-02-06 18:20 UTC, li-jin-gou commented on cmd/net/readme.md
> +go run main.go -targer-dir ./haha
go install 的方式执行

2024-02-06 18:21 UTC, li-jin-gou commented on cmd/net/readme.md
> +go run main.go -targer-dir ./haha
添加一个 version 这个工具后面应该用户挺多的。

2024-02-06 18:22 UTC, li-jin-gou commented on cmd/net/readme.md
> +### change all go file in target dir
完善 readme

2024-02-06 18:22 UTC, li-jin-gou commented on cmd/net/internal/logic/netHttp/utils_test.go
> +package netHttp
空文件

2024-02-07 05:43 UTC, li-jin-gou commented on cmd/tool/readme.md
> +go install github.com/hertz-contrib/migrate/cmd/tool@latest
hertz_migrate_tool 更合理一些？

2024-02-07 05:45 UTC, li-jin-gou commented on cmd/tool/readme.md
> +tool -target-dir ./haha
?

2024-02-07 05:45 UTC, li-jin-gou commented on cmd/tool/t
> +                                 Apache License
额外的文件

2024-02-07 06:11 UTC, li-jin-gou commented on cmd/tool/internal/utils/cli.go
> +	cmd := exec.Command("go", "get", "-u", repo)
-u 会导致不兼容情况

2024-02-07 06:11 UTC, li-jin-gou commented on cmd/tool/internal/utils/cli.go
> +	cmd := exec.Command("go", "get", "-u", repo)
-u 去掉 更合理

2024-02-07 06:11 UTC, li-jin-gou commented on cmd/tool/internal/args/args.go
> +	PrintMode string
PrintMode 和 Debug 的作用是？

2024-02-07 06:12 UTC, li-jin-gou commented on cmd/tool/readme.md
> +### How to use
完善各参数的作用

2024-02-07 06:13 UTC, Skyenought commented on cmd/tool/internal/args/args.go
> +	PrintMode string
我留下来自用的

2024-02-07 07:29 UTC, li-jin-gou approved these changes

2024-02-07 07:29 UTC, merged